# WORKFLOW WITH 2 JOBS
# name: GitHub Action

# on:
#   workflow_dispatch:

# jobs:
#   deploy1:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

      # - name: Build Docker image
      #   run: |
      #     docker build -t "${{ secrets.IMAGE_NAME }}" .
      #     docker login --username "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
      #     docker push "${{ secrets.IMAGE_NAME }}"

  #     - name: Install OpenVPN3
  #       run: |
  #         sudo mkdir -p /etc/apt/keyrings && curl -fsSL https://packages.openvpn.net/packages-repo.gpg | sudo tee /etc/apt/keyrings/openvpn.asc
  #         DISTRO=$(lsb_release -c | awk '{print $2}')
  #         echo "deb [signed-by=/etc/apt/keyrings/openvpn.asc] https://packages.openvpn.net/openvpn3/debian $DISTRO main" | sudo tee /etc/apt/sources.list.d/openvpn-packages.list
  #         sudo apt update
  #         sudo apt install -y openvpn3

  #     - name: Connect to OpenVPN
  #       run: |
  #         printf "${{ secrets.USER }}\n${{ secrets.PASSWORD }}" | openvpn3 session-start --config .github/workflows/client.ovpn | grep 'Session path' | cut -d' ' -f3 > session_path.txt
  #         SESSION_PATH=$(cat session_path.txt)
  #         echo "SESSION_PATH=$SESSION_PATH" >> $GITHUB_ENV
  #         echo "SESSION_PATH=$SESSION_PATH"

  #     - name: Upload session path as artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: session-path
  #         path: session_path.txt

  #     - name: session-list
  #       run: |
  #         openvpn3 sessions-list
  # deploy2:
  #   needs: deploy1
  #   runs-on: ubuntu-latest
  #   steps:
      # - name: Use SSH
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: "${{ secrets.DEMO_IP }}"
      #     username: "${{ secrets.DEMO_USERNAME }}"
      #     key: ${{ secrets.DEV_SSH_KEY }}
      #     port: "${{ secrets.PORT }}"
      #     script: |
      #       docker login --username "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
      #       docker pull "${{ secrets.IMAGE_NAME }}"
      #       docker run --name "${{ secrets.CONTAINER_NAME }}" -p 4202:80 -d --rm "${{ secrets.IMAGE_NAME }}"

      # - name: Download session path artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: session-path

      # - name: Disconnect from OpenVPN
      #   run: |
      #     SESSION_PATH=$(cat session_path.txt)
      #     echo "SESSION_PATH=$SESSION_PATH"
      #     openvpn3 session-manage --session-path "$SESSION_PATH" --disconnect

# Workflow with 1 job
name: GitHub Action

on:
  workflow_dispatch:

jobs:
  deploy1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Build Docker image
      #   run: |
      #     docker build -t "${{ secrets.IMAGE_NAME }}" .
      #     docker login --username "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
      #     docker push "${{ secrets.IMAGE_NAME }}"

      - name: Install OpenVPN3
        run: |
          sudo mkdir -p /etc/apt/keyrings && curl -fsSL https://packages.openvpn.net/packages-repo.gpg | sudo tee /etc/apt/keyrings/openvpn.asc
          DISTRO=$(lsb_release -c | awk '{print $2}')
          echo "deb [signed-by=/etc/apt/keyrings/openvpn.asc] https://packages.openvpn.net/openvpn3/debian $DISTRO main" | sudo tee /etc/apt/sources.list.d/openvpn-packages.list
          sudo apt update
          sudo apt install -y openvpn3

      - name: Connect to OpenVPN
        run: |
          printf "${{ secrets.USER }}\n${{ secrets.PASSWORD }}" | openvpn3 session-start --config .github/workflows/client.ovpn | grep 'Session path' | cut -d' ' -f3 > session_path.txt
          SESSION_PATH=$(cat session_path.txt)
          echo "SESSION_PATH=$SESSION_PATH" >> $GITHUB_ENV
          echo "SESSION_PATH=$SESSION_PATH"

      - name: session-list
        run: |
          openvpn3 sessions-list

      # - name: Use SSH
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: "${{ secrets.DEMO_IP }}"
      #     username: "${{ secrets.DEMO_USERNAME }}"
      #     key: ${{ secrets.DEV_SSH_KEY }}
      #     port: "${{ secrets.PORT }}"
      #     script: |
      #       docker login --username "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
      #       docker pull "${{ secrets.IMAGE_NAME }}"
      #       docker run --name "${{ secrets.CONTAINER_NAME }}" -p 4202:80 -d --rm "${{ secrets.IMAGE_NAME }}"

      - name: Disconnect from OpenVPN
        run: |
          echo "Session path = $SESSION_PATH"
          openvpn3 session-manage --session-path $SESSION_PATH --disconnect
