name: GitHub Action

on:
  workflow_dispatch:

jobs:
  deploy1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install OpenVPN3
        run: |
          sudo mkdir -p /etc/apt/keyrings && curl -fsSL https://packages.openvpn.net/packages-repo.gpg | sudo tee /etc/apt/keyrings/openvpn.asc
          DISTRO=$(lsb_release -c | awk '{print $2}')
          echo "deb [signed-by=/etc/apt/keyrings/openvpn.asc] https://packages.openvpn.net/openvpn3/debian $DISTRO main" | sudo tee /etc/apt/sources.list.d/openvpn-packages.list
          sudo apt update
          sudo apt install -y openvpn3

      - name: Connect to OpenVPN
        run: |
          printf "${{ secrets.USER }}\n${{ secrets.PASSWORD }}" | openvpn3 session-start --config .github/workflows/client.ovpn | grep 'Session path' | cut -d' ' -f3 > session_path.txt
          SESSION_PATH=$(cat session_path.txt)
          echo "SESSION_PATH=$SESSION_PATH" >> $GITHUB_ENV
          echo "SESSION_PATH=$SESSION_PATH"
          echo "VPN connected successfully"
   
      - name: Use SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEMO_IP }}
          username: ${{ secrets.DEMO_USERNAME }}
          key: ${{ secrets.DEV_SSH_KEY }}
          # port: ${{ secrets.PORT }}
          script: |
            docker login --username "${{ secrets.DOCKER_USERNAME}}" --password "${{ secrets.DOCKER_PASSWORD}}"
            docker pull yogeshyp/sampleclient:latest
            docker run --name sample -p 4202:80 -d --rm sampleclient:latest

      - name: Disconnect from OpenVPN
        run: |
          echo "Session Path: $SESSION_PATH"
          openvpn3 session-manage --session-path "$SESSION_PATH" --disconnect

      # - name: session
      #   run: |
      #     echo "${{ secrets.DEMO_IP }}"
      #     echo "${{ secrets.DEMO_USERNAME }}"
      #     # echo "${{ secrets.DEV_SSH_KEY }}"
      #     openvpn3 sessions-list